// Asset name mapping for readable display
export const ASSET_NAMES: Record<string, string> = {
  // Crypto
  BTCUSDT: "Bitcoin",
  ETHUSDT: "Ethereum",
  BNBUSDT: "BNB",
  SOLUSDT: "Solana",
  XRPUSDT: "Ripple",
  ADAUSDT: "Cardano",
  DOGEUSDT: "Dogecoin",
  TRXUSDT: "Tron",
  AVAXUSDT: "Avalanche",
  LINKUSDT: "Chainlink",
  DOTUSDT: "Polkadot",
  MATICUSDT: "Polygon",
  UNIUSDT: "Uniswap",
  LTCUSDT: "Litecoin",
  XLMUSDT: "Stellar",
  ATOMUSDT: "Cosmos",
  FILUSDT: "Filecoin",
  NEARUSDT: "Near Protocol",
  APTUSDT: "Aptos",
  SUIUSDT: "Sui",
  CRVUSDT: "Curve",
  AAVEUSDT: "Aave",
  EIGENUSDT: "EigenLayer",
  RNDRUSDT: "Render",

  // Commodities (Yahoo Finance symbols)
  "GC=F": "Gold",
  "SI=F": "Silver",
  "PL=F": "Platinum",
  "PA=F": "Palladium",
  "HG=F": "Copper",
  "CL=F": "Crude Oil",
  "NG=F": "Natural Gas",

  // Magnificent Seven
  AAPL: "Apple",
  MSFT: "Microsoft",
  NVDA: "NVIDIA",
  AMZN: "Amazon",
  GOOGL: "Alphabet",
  META: "Meta",
  TSLA: "Tesla",

  // Technology - Mega Caps
  AVGO: "Broadcom",
  ADBE: "Adobe",
  "BRK-B": "Berkshire Hathaway",
  LLY: "Eli Lilly",
  V: "Visa",
  UNH: "UnitedHealth",
  XOM: "Exxon Mobil",
  WMT: "Walmart",
  JNJ: "Johnson & Johnson",
  ORCL: "Oracle",
  COST: "Costco",
  MA: "Mastercard",
  PG: "Procter & Gamble",
  NFLX: "Netflix",
  PEP: "PepsiCo",
  CSCO: "Cisco",
  AMD: "AMD",
  INTC: "Intel",
  QCOM: "Qualcomm",
  TXN: "Texas Instruments",
  AMAT: "Applied Materials",
  INTU: "Intuit",
  ISRG: "Intuitive Surgical",
  BKNG: "Booking Holdings",
  MU: "Micron",
  LRCX: "Lam Research",
  KLAC: "KLA Corp",
  ASML: "ASML",
  MRVL: "Marvell",
  SNPS: "Synopsys",
  CDNS: "Cadence",
  ORLY: "O'Reilly Auto",
  REGN: "Regeneron",
  VRTX: "Vertex",
  MDLZ: "Mondelez",
  SBUX: "Starbucks",
  GILD: "Gilead",
  ADI: "Analog Devices",
  PANW: "Palo Alto Networks",
  CRWD: "CrowdStrike",
  FTNT: "Fortinet",
  ADP: "ADP",
  PYPL: "PayPal",
  ABNB: "Airbnb",
  MAR: "Marriott",
  CTAS: "Cintas",
  NXPI: "NXP Semiconductors",
  ROP: "Roper Technologies",
  AEP: "American Electric",
  EXC: "Exelon",
  PAYX: "Paychex",
  ODFL: "Old Dominion Freight",
  FAST: "Fastenal",
  IDXX: "IDEXX Labs",
  BIIB: "Biogen",
  EA: "Electronic Arts",
  TTWO: "Take-Two",
  MNST: "Monster Beverage",
  DLTR: "Dollar Tree",
  ROST: "Ross Stores",
  KDP: "Keurig Dr Pepper",
  PCAR: "PACCAR",
  XEL: "Xcel Energy",
  WDAY: "Workday",
  ZS: "Zscaler",
  DDOG: "Datadog",
  MDB: "MongoDB",
  TEAM: "Atlassian",
  SHOP: "Shopify",
  UBER: "Uber",
  LYFT: "Lyft",

  // Financials
  JPM: "JPMorgan Chase",
  BAC: "Bank of America",
  WFC: "Wells Fargo",
  GS: "Goldman Sachs",
  MS: "Morgan Stanley",
  C: "Citigroup",
  AXP: "American Express",
  BLK: "BlackRock",
  SCHW: "Charles Schwab",
  PNC: "PNC Financial",
  USB: "U.S. Bancorp",
  TFC: "Truist",
  COF: "Capital One",
  BK: "Bank of New York",
  STT: "State Street",
  AMP: "Ameriprise",
  NTRS: "Northern Trust",
  CFG: "Citizens Financial",
  KEY: "KeyCorp",
  FITB: "Fifth Third",
  RF: "Regions Financial",
  HBAN: "Huntington",
  CMA: "Comerica",
  ZION: "Zions Bank",
  MTB: "M&T Bank",

  // Communications/Tech Services
  T: "AT&T",
  VZ: "Verizon",
  CMCSA: "Comcast",
  DIS: "Disney",
  CRM: "Salesforce",
  NOW: "ServiceNow",
  IBM: "IBM",
  ACN: "Accenture",
  SPGI: "S&P Global",

  // Insurance
  MMC: "Marsh McLennan",
  CB: "Chubb",
  AIG: "AIG",
  TRV: "Travelers",
  AFL: "Aflac",
  PRU: "Prudential",
  MET: "MetLife",
  ALL: "Allstate",

  // Healthcare
  DHR: "Danaher",
  ABT: "Abbott",
  TMO: "Thermo Fisher",
  SYK: "Stryker",
  MDT: "Medtronic",
  BMY: "Bristol-Myers",
  PFE: "Pfizer",
  MRK: "Merck",
  ABBV: "AbbVie",
  AMGN: "Amgen",
  CVS: "CVS Health",
  CI: "Cigna",
  HUM: "Humana",
  UHS: "Universal Health",
  HCA: "HCA Healthcare",
  ELV: "Elevance Health",
  CNC: "Centene",
  DVA: "DaVita",
  ZBH: "Zimmer Biomet",
  BDX: "BD",
  BAX: "Baxter",
  BSX: "Boston Scientific",
  EW: "Edwards Lifesciences",
  HOLX: "Hologic",
  DXCM: "DexCom",
  ALGN: "Align Technology",
  A: "Agilent",
  IQV: "IQVIA",
  MTD: "Mettler-Toledo",
  WAT: "Waters Corp",
  TER: "Teradyne",
  KEYS: "Keysight",
  MCHP: "Microchip",
  ON: "ON Semiconductor",
  SWKS: "Skyworks",
  MPWR: "Monolithic Power",

  // Consumer
  KO: "Coca-Cola",
  MCD: "McDonald's",
  NKE: "Nike",
  TGT: "Target",
  HD: "Home Depot",
  LOW: "Lowe's",
  TJX: "TJX Companies",
  CMG: "Chipotle",
  YUM: "Yum! Brands",
  DPZ: "Domino's",
  DRI: "Darden",
  F: "Ford",
  GM: "General Motors",
  HON: "Honeywell",
  GE: "GE Aerospace",
  CAT: "Caterpillar",
  DE: "Deere",
  RTX: "RTX Corp",
  LMT: "Lockheed Martin",
  NOC: "Northrop Grumman",
  BA: "Boeing",
  UPS: "UPS",
  FDX: "FedEx",

  // Utilities
  NEE: "NextEra Energy",
  DUK: "Duke Energy",
  SO: "Southern Company",
  D: "Dominion Energy",
  SRE: "Sempra",
  PEG: "PSEG",
  ED: "Con Edison",
  WEC: "WEC Energy",
  ES: "Eversource",
  AWK: "American Water",
  ATO: "Atmos Energy",

  // Growth Stocks
  FIGS: "FIGS Inc",
  XPEV: "XPeng",
  RIVN: "Rivian",
  SOFI: "SoFi",
  ENPH: "Enphase Energy",
  SEDG: "SolarEdge",
  WDC: "Western Digital",

  // Technology Growth
  PLTR: "Palantir",
  SNOW: "Snowflake",
  NET: "Cloudflare",
  OKTA: "Okta",
  GTLB: "GitLab",
  PATH: "UiPath",
  DOCN: "DigitalOcean",
  CFLT: "Confluent",
  ESTC: "Elastic",
  BILL: "Bill.com",
  HUBS: "HubSpot",
  TWLO: "Twilio",
  DOCU: "DocuSign",
  ZEN: "Zendesk",
  SMAR: "Smartsheet",
  MNDY: "Monday.com",
  PCTY: "Paylocity",
  PAYC: "Paycom",
  FIVN: "Five9",
  NICE: "NICE Ltd",
  COUP: "Coupa Software",
  DT: "Dynatrace",
  FRSH: "Freshworks",
  SUMO: "Sumo Logic",
  TENB: "Tenable",
  VRNS: "Varonis",
  QLYS: "Qualys",
  RPD: "Rapid7",
  NCNO: "nCino",
  DBX: "Dropbox",
  LSPD: "Lightspeed Commerce",
  WEAV: "Weave",
  BRZE: "Braze",
  AMPL: "Amplitude",
  AI: "C3.ai",
  BBAI: "BigBear.ai",
  IONQ: "IonQ",
  RGTI: "Rigetti Computing",
  QUBT: "Quantum Computing",
  TOST: "Toast",
  FOUR: "Shift4 Payments",
  FLYW: "Flywire",
  PSFE: "Paysafe",
  OLO: "Olo",
  TASK: "TaskUs",
  COUR: "Coursera",
  UDMY: "Udemy",
  DUOL: "Duolingo",
  CHGG: "Chegg",
  U: "Unity Software",
  RBLX: "Roblox",
  ZI: "ZoomInfo",
  S: "SentinelOne",
  FSLY: "Fastly",
  APPF: "AppFolio",
  PD: "PagerDuty",
  APP: "AppLovin",

  // Healthcare/Biotech
  VEEV: "Veeva Systems",
  HIMS: "Hims & Hers",
  DOCS: "Doximity",
  RXRX: "Recursion",
  TDOC: "Teladoc",
  NBIX: "Neurocrine",
  AXSM: "Axsome",
  MRNA: "Moderna",
  BNTX: "BioNTech",
  NVAX: "Novavax",
  BEAM: "Beam Therapeutics",
  EDIT: "Editas Medicine",
  NTLA: "Intellia",
  CRSP: "CRISPR",
  EXAS: "Exact Sciences",
  ILMN: "Illumina",
  NTRA: "Natera",
  TXG: "10x Genomics",
  SDGR: "Schrodinger",
  LEGN: "Legend Biotech",
  ALNY: "Alnylam",
  IONS: "Ionis",
  SRPT: "Sarepta",
  BMRN: "BioMarin",
  GH: "Guardant Health",
  TWST: "Twist Bioscience",
  VCYT: "Veracyte",
  MYGN: "Myriad Genetics",
  RGEN: "Repligen",
  MEDP: "Medpace",
  DNLI: "Denali",
  ARVN: "Arvinas",
  RCKT: "Rocket Pharma",
  RARE: "Ultragenyx",
  KURA: "Kura Oncology",
  APLS: "Apellis",
  ARWR: "Arrowhead",
  PCVX: "Vaxcyte",
  IOVA: "Iovance",
  BLUE: "Bluebird Bio",
  FATE: "Fate Therapeutics",
  SRRK: "Scholar Rock",
  KRYS: "Krystal Biotech",
  PTCT: "PTC Therapeutics",
  VKTX: "Viking Therapeutics",
  VRNA: "Verona Pharma",
  BHVN: "Biohaven",
  CERT: "Certara",
  GTHX: "G1 Therapeutics",
  BBIO: "BridgeBio",

  // Consumer Discretionary
  CROX: "Crocs",
  SHAK: "Shake Shack",
  BROS: "Dutch Bros",
  BIRD: "Allbirds",
  RVLV: "Revolve",
  LULU: "Lululemon",
  DECK: "Deckers",
  ONON: "On Holding",
  GOOS: "Canada Goose",
  WRBY: "Warby Parker",
  PLBY: "PLBY Group",
  PRKS: "United Parks",
  ASO: "Academy Sports",
  DKS: "Dick's Sporting",
  HIBB: "Hibbett",
  COLM: "Columbia",
  PVH: "PVH Corp",
  RL: "Ralph Lauren",
  TPR: "Tapestry",
  CPRI: "Capri Holdings",
  VFC: "VF Corp",
  HBI: "Hanesbrands",
  UAA: "Under Armour",
  SKX: "Skechers",
  NIO: "NIO",
  LI: "Li Auto",
  LCID: "Lucid Motors",
  FSR: "Fisker",
  NKLA: "Nikola",
  WKHS: "Workhorse",
  GOEV: "Canoo",
  NRDY: "Nerdy",
  SFIX: "Stitch Fix",
  RENT: "Rent the Runway",
  CHWY: "Chewy",
  W: "Wayfair",
  ETSY: "Etsy",
  CVNA: "Carvana",
  WISH: "ContextLogic",

  // Fintech
  HOOD: "Robinhood",
  UPST: "Upstart",
  AFRM: "Affirm",
  LC: "LendingClub",
  LMND: "Lemonade",
  ROOT: "Root Insurance",
  MQ: "Marqeta",
  PAYO: "Payoneer",
  DLO: "DLocal",
  RELY: "Remitly",
  NU: "Nu Holdings",
  COIN: "Coinbase",
  MARA: "Marathon Digital",
  RIOT: "Riot Platforms",
  CLSK: "CleanSpark",
  HUT: "Hut 8 Mining",
  BTBT: "Bit Digital",
  CIFR: "Cipher Mining",
  HIVE: "HIVE Blockchain",
  BITF: "Bitfarms",
  CORZ: "Core Scientific",
  WULF: "TeraWulf",
  SQ: "Block",
  OPEN: "Opendoor",
  RDFN: "Redfin",
  RKT: "Rocket Companies",
  UWMC: "UWM Holdings",
  TREE: "LendingTree",
  LDI: "loanDepot",
  GHLD: "Guild Holdings",
  CLOV: "Clover Health",
  OSCR: "Oscar Health",
  ACHR: "Archer Aviation",

  // Industrials/Aerospace
  RKLB: "Rocket Lab",
  JOBY: "Joby Aviation",
  LILM: "Lilium",
  SPCE: "Virgin Galactic",
  ASTS: "AST SpaceMobile",
  LUNR: "Intuitive Machines",
  ASTR: "Astra Space",
  RDW: "Redwire",
  PLUG: "Plug Power",
  FCEL: "FuelCell Energy",
  BLDP: "Ballard Power",
  BE: "Bloom Energy",
  BLBD: "Blue Bird",
  LEV: "Lion Electric",
  VLTA: "Volta Inc",
  HYLN: "Hyliion",
  XL: "XL Fleet",
  PTRA: "Proterra",
  ARVL: "Arrival",
  REE: "REE Automotive",
  EVTV: "Envirotech",
  HYZN: "Hyzon Motors",
  LDOS: "Leidos",
  KTOS: "Kratos Defense",
  RCAT: "Red Cat",
  UAVS: "AgEagle Aerial",
  EH: "EHang",
  BWXT: "BWX Technologies",

  // Clean Energy
  RUN: "Sunrun",
  NOVA: "Sunnova",
  FSLR: "First Solar",
  ARRY: "Array Technologies",
  STEM: "Stem Inc",
  CHPT: "ChargePoint",
  EVGO: "EVgo",
  BLNK: "Blink Charging",
  DCFC: "Tritium",
  QS: "QuantumScape",
  GEVO: "Gevo",
  AMTX: "Aemetis",
  CLNE: "Clean Energy Fuels",
  LICY: "Li-Cycle",
  FREYR: "FREYR Battery",
  MAXN: "Maxeon Solar",
  CSIQ: "Canadian Solar",
  JKS: "JinkoSolar",
  DQ: "Daqo New Energy",
  SPWR: "SunPower",
  EOSE: "Eos Energy",
  FLNC: "Fluence Energy",
  BEEM: "Beam Global",

  // Communications/Media
  ROKU: "Roku",
  TTD: "Trade Desk",
  MGNI: "Magnite",
  PUBM: "PubMatic",
  IAS: "Integral Ad Science",
  DV: "DoubleVerify",
  APPS: "Digital Turbine",
  GENI: "Genius Sports",
  SKLZ: "Skillz",
  DKNG: "DraftKings",
  PENN: "Penn Entertainment",
  RSI: "Rush Street",
  FUBO: "FuboTV",
  PARA: "Paramount",
  WBD: "Warner Bros Discovery",
  LYV: "Live Nation",
  SPOT: "Spotify",
  SIRI: "SiriusXM",
  IHRT: "iHeartMedia",
  ATUS: "Altice USA",

  // Real Estate
  ZG: "Zillow",
  EXPI: "eXp World",
  COMP: "Compass",
  OPAD: "Offerpad",
  DOOR: "Masonite",
  HOUS: "Anywhere Real Estate",
  OPRT: "Oportun",
  REAX: "Real Brokerage",
  RMAX: "RE/MAX",
  REAL: "RealReal",
  FYBR: "Frontier Communications",

  // Indices
  "^GSPC": "S&P 500",
  "^RUT": "Russell 2000",
  "^NDX": "NASDAQ 100",
  "^DJI": "Dow Jones",
  "^VIX": "VIX Volatility",

  // ETFs
  SPY: "S&P 500 ETF",
  IWM: "Russell 2000 ETF",
  QQQ: "NASDAQ 100 ETF",
  DIA: "Dow Jones ETF",
  XLF: "Financial Select Sector",
  XLK: "Technology Select Sector",
  XLE: "Energy Select Sector",
  XLV: "Health Care Select Sector",
  XLI: "Industrial Select Sector",
  XLY: "Consumer Discretionary",
  XLP: "Consumer Staples",
  XLB: "Materials Select Sector",
  XLU: "Utilities Select Sector",
  GLD: "SPDR Gold Trust",
  SLV: "iShares Silver Trust",
  USO: "United States Oil Fund",
  TLT: "iShares 20+ Year Treasury",
  HYG: "iShares High Yield Bond",
  LQD: "iShares Investment Grade Bond",
  VNQ: "Vanguard Real Estate",
  ARKK: "ARK Innovation ETF",
  ARKG: "ARK Genomic Revolution",
  SOXL: "Semiconductor Bull 3X",
  TQQQ: "ProShares UltraPro QQQ",
  UVXY: "ProShares Ultra VIX",
  IVV: "iShares Core S&P 500",
  IEFA: "iShares Core MSCI EAFE",
  AGG: "iShares Core Aggregate Bond",
  IJH: "iShares Core S&P Mid-Cap",
  IJR: "iShares Core S&P Small-Cap",
  EFA: "iShares MSCI EAFE",
  EEM: "iShares MSCI Emerging",
  IWF: "iShares Russell 1000 Growth",
  IWD: "iShares Russell 1000 Value",
  TIP: "iShares TIPS Bond",
  IWB: "iShares Russell 1000",
  IWN: "iShares Russell 2000 Value",
  IWO: "iShares Russell 2000 Growth",
  IEMG: "iShares Core MSCI EM",
  ITOT: "iShares Core S&P Total",
  IXUS: "iShares Core MSCI Total Intl",
  SHY: "iShares 1-3 Year Treasury",

  // Metals (alternative symbols)
  XAUUSD: "Gold",
  XAGUSD: "Silver",
  XPTUSD: "Platinum",
  XPDUSD: "Palladium",
  XCUUSD: "Copper",

  // Rare Earths
  MP: "MP Materials",
  LYSCF: "Lynas Rare Earths",
  ILHMF: "Iluka Resources",
  REMX: "Rare Earth ETF",
};

export function getAssetName(symbol: string): string {
  return ASSET_NAMES[symbol] || symbol;
}
