project_id = "qceatovcjqhiqdpgfdzm"

[functions.fetch-news]
verify_jwt = false

[functions.fetch-stock-data]
verify_jwt = false

[functions.trading-ai-chat]
verify_jwt = true

[functions.crypto-insight]
verify_jwt = false

[functions.market-collector]
verify_jwt = false
